/**
 * TypeScript scraper that runs inside Next.js API routes (works on Vercel).
 * Uses curated product data for all 5 Irish supermarkets.
 */

export interface ScrapedProduct {
  name: string;
  price: number;
  originalPrice?: number;
  isOnSale?: boolean;
  unitPrice?: number;
  unitPriceUnit?: string;
  brand?: string;
  category?: string;
  weight?: number;
  weightUnit?: string;
  barcode?: string;
  imageUrl?: string;
  sourceUrl?: string;
  description?: string;
}

/* ------------------------------------------------------------------ */
/*  Curated product data for each store                                */
/* ------------------------------------------------------------------ */

const TESCO_PRODUCTS: ScrapedProduct[] = [
  // ── dairy & eggs (20) ──
  { name: "Tesco Irish Whole Milk 2L", price: 1.95, brand: "Tesco", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Tesco Low Fat Milk 2L", price: 1.89, brand: "Tesco", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Tesco Whole Milk 1L", price: 1.25, brand: "Tesco", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Tesco Skimmed Milk 1L", price: 1.19, brand: "Tesco", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Kerrygold Pure Irish Butter 227g", price: 2.89, brand: "Kerrygold", category: "dairy & eggs", weight: 227, weightUnit: "g" },
  { name: "Tesco Spreadable Butter 500g", price: 3.59, brand: "Tesco", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Tesco Mild Cheddar Cheese 200g", price: 2.15, brand: "Tesco", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Tesco Mature Cheddar Cheese 200g", price: 2.45, brand: "Tesco", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Tesco Grated Mozzarella 250g", price: 1.79, brand: "Tesco", category: "dairy & eggs", weight: 250, weightUnit: "g" },
  { name: "Glenisk Organic Natural Yoghurt 500g", price: 2.49, brand: "Glenisk", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Tesco Greek Style Yoghurt 500g", price: 1.59, brand: "Tesco", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Tesco Natural Yoghurt 500g", price: 1.09, brand: "Tesco", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Tesco Free Range Eggs 10 Pack", price: 3.19, brand: "Tesco", category: "dairy & eggs", weight: 10, weightUnit: "units" },
  { name: "Tesco Free Range Eggs 6 Pack", price: 2.09, brand: "Tesco", category: "dairy & eggs", weight: 6, weightUnit: "units" },
  { name: "Tesco Fresh Cream 250ml", price: 1.39, brand: "Tesco", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Tesco Double Cream 250ml", price: 1.59, brand: "Tesco", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Tesco Cottage Cheese 300g", price: 1.89, brand: "Tesco", category: "dairy & eggs", weight: 300, weightUnit: "g" },
  { name: "Tesco Cream Cheese 200g", price: 1.49, brand: "Tesco", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Tesco Sliced Cheese 150g", price: 1.69, brand: "Tesco", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  { name: "Tesco Parmesan Wedge 150g", price: 3.29, brand: "Tesco", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  // ── meat & poultry (15) ──
  { name: "Tesco Irish Chicken Breast Fillets 360g", price: 4.69, brand: "Tesco", category: "meat & poultry", weight: 360, weightUnit: "g" },
  { name: "Tesco Irish Chicken Thighs 500g", price: 3.49, brand: "Tesco", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Tesco Irish Chicken Drumsticks 500g", price: 2.89, brand: "Tesco", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Tesco Whole Irish Chicken 1.5kg", price: 5.99, brand: "Tesco", category: "meat & poultry", weight: 1.5, weightUnit: "kg" },
  { name: "Tesco Irish Beef Mince 400g", price: 4.19, brand: "Tesco", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Tesco Irish Beef Mince 750g", price: 6.79, brand: "Tesco", category: "meat & poultry", weight: 750, weightUnit: "g" },
  { name: "Tesco Irish Beef Steak 250g", price: 5.49, brand: "Tesco", category: "meat & poultry", weight: 250, weightUnit: "g" },
  { name: "Tesco Streaky Bacon Rashers 200g", price: 2.49, brand: "Tesco", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Tesco Back Bacon Rashers 200g", price: 2.99, brand: "Tesco", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Tesco Irish Pork Sausages 454g", price: 2.69, brand: "Tesco", category: "meat & poultry", weight: 454, weightUnit: "g" },
  { name: "Tesco Cooked Ham Slices 200g", price: 2.89, brand: "Tesco", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Tesco Smoked Salmon 100g", price: 4.29, brand: "Tesco", category: "meat & poultry", weight: 100, weightUnit: "g" },
  { name: "Tesco Fresh Salmon Fillets 260g", price: 5.49, brand: "Tesco", category: "meat & poultry", weight: 260, weightUnit: "g" },
  { name: "Tesco Irish Turkey Mince 400g", price: 3.99, brand: "Tesco", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Tesco Lamb Leg Steak 200g", price: 4.99, brand: "Tesco", category: "meat & poultry", weight: 200, weightUnit: "g" },
  // ── fruits & vegetables (20) ──
  { name: "Tesco Bananas 5 Pack", price: 1.09, brand: "Tesco", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Tesco Royal Gala Apples 6 Pack", price: 1.99, brand: "Tesco", category: "fruits & vegetables", weight: 6, weightUnit: "units" },
  { name: "Tesco Broccoli Head", price: 1.09, brand: "Tesco", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Tesco Carrots 1kg", price: 0.89, brand: "Tesco", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Tesco Rooster Potatoes 2.5kg", price: 2.69, brand: "Tesco", category: "fruits & vegetables", weight: 2.5, weightUnit: "kg" },
  { name: "Tesco White Potatoes 2kg", price: 1.89, brand: "Tesco", category: "fruits & vegetables", weight: 2, weightUnit: "kg" },
  { name: "Tesco Iceberg Lettuce", price: 0.99, brand: "Tesco", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Tesco Vine Tomatoes 450g", price: 1.59, brand: "Tesco", category: "fruits & vegetables", weight: 450, weightUnit: "g" },
  { name: "Tesco Brown Onions 1kg", price: 0.99, brand: "Tesco", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Tesco Closed Cup Mushrooms 250g", price: 1.29, brand: "Tesco", category: "fruits & vegetables", weight: 250, weightUnit: "g" },
  { name: "Tesco Red Peppers 3 Pack", price: 1.79, brand: "Tesco", category: "fruits & vegetables", weight: 3, weightUnit: "units" },
  { name: "Tesco Avocados 2 Pack", price: 1.99, brand: "Tesco", category: "fruits & vegetables", weight: 2, weightUnit: "units" },
  { name: "Tesco Strawberries 400g", price: 2.99, brand: "Tesco", category: "fruits & vegetables", weight: 400, weightUnit: "g" },
  { name: "Tesco Blueberries 150g", price: 2.49, brand: "Tesco", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Tesco Raspberries 150g", price: 2.99, brand: "Tesco", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Tesco Cucumber", price: 0.79, brand: "Tesco", category: "fruits & vegetables", weight: 1, weightUnit: "units" },
  { name: "Tesco Baby Spinach 100g", price: 1.69, brand: "Tesco", category: "fruits & vegetables", weight: 100, weightUnit: "g" },
  { name: "Tesco Courgettes 500g", price: 1.29, brand: "Tesco", category: "fruits & vegetables", weight: 500, weightUnit: "g" },
  { name: "Tesco Lemons 5 Pack", price: 1.49, brand: "Tesco", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Tesco Mixed Salad Bag 120g", price: 1.59, brand: "Tesco", category: "fruits & vegetables", weight: 120, weightUnit: "g" },
  // ── bakery (12) ──
  { name: "Tesco White Sliced Pan 800g", price: 1.35, brand: "Tesco", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Tesco Wholemeal Sliced Pan 800g", price: 1.45, brand: "Tesco", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Family Pan 800g", price: 2.09, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Wholemeal Bread 800g", price: 2.19, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Tesco 4 Butter Croissants", price: 1.69, brand: "Tesco", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Tesco Sourdough Bread 500g", price: 1.99, brand: "Tesco", category: "bakery", weight: 500, weightUnit: "g" },
  { name: "Tesco Soft White Rolls 6 Pack", price: 1.29, brand: "Tesco", category: "bakery", weight: 6, weightUnit: "units" },
  { name: "Tesco Tortilla Wraps 8 Pack", price: 1.59, brand: "Tesco", category: "bakery", weight: 8, weightUnit: "units" },
  { name: "Tesco Scones 4 Pack", price: 1.49, brand: "Tesco", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Tesco Bagels 5 Pack", price: 1.39, brand: "Tesco", category: "bakery", weight: 5, weightUnit: "units" },
  { name: "Tesco Garlic Bread Baguette 270g", price: 1.49, brand: "Tesco", category: "bakery", weight: 270, weightUnit: "g" },
  { name: "Johnston Mooney & OBrien Batch Loaf 800g", price: 2.29, brand: "Johnston Mooney", category: "bakery", weight: 800, weightUnit: "g" },
  // ── drinks (20) ──
  { name: "Tesco Still Water 2L", price: 0.55, brand: "Tesco", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Tesco Still Water 500ml", price: 0.39, brand: "Tesco", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Tesco Orange Juice 1L", price: 1.85, brand: "Tesco", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tesco Apple Juice 1L", price: 1.59, brand: "Tesco", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Barry's Gold Blend Tea 80s", price: 4.29, brand: "Barry's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Lyon's Original Tea 80s", price: 3.99, brand: "Lyon's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Nescafé Original Instant Coffee 200g", price: 6.99, brand: "Nescafé", category: "drinks", weight: 200, weightUnit: "g" },
  { name: "Coca-Cola 2L", price: 2.85, brand: "Coca-Cola", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Coca-Cola 6 Pack 330ml", price: 4.99, brand: "Coca-Cola", category: "drinks", weight: 6, weightUnit: "units" },
  { name: "Tesco Cola 2L", price: 0.95, brand: "Tesco", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Club Orange 2L", price: 2.49, brand: "Club", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Lucozade Energy Original 1L", price: 2.69, brand: "Lucozade", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Monster Energy 500ml", price: 1.99, brand: "Monster", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Tesco Oat Milk 1L", price: 1.79, brand: "Tesco", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tesco Almond Milk 1L", price: 1.69, brand: "Tesco", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tesco Sparkling Water 2L", price: 0.55, brand: "Tesco", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Robinsons Orange Squash 1L", price: 2.49, brand: "Robinsons", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tropicana Orange Juice 950ml", price: 3.49, brand: "Tropicana", category: "drinks", weight: 950, weightUnit: "ml" },
  { name: "Tesco Cranberry Juice 1L", price: 1.89, brand: "Tesco", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Ballygowan Still Water 2L", price: 1.29, brand: "Ballygowan", category: "drinks", weight: 2, weightUnit: "l" },
  // ── frozen (15) ──
  { name: "Birds Eye Fish Fingers 450g", price: 3.99, brand: "Birds Eye", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Tesco Fish Fingers 450g", price: 2.79, brand: "Tesco", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Tesco Frozen Pizza Margherita 300g", price: 1.89, brand: "Tesco", category: "frozen", weight: 300, weightUnit: "g" },
  { name: "Chicago Town Pepperoni Pizza 400g", price: 3.49, brand: "Chicago Town", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Tesco Frozen Chips 1.5kg", price: 2.19, brand: "Tesco", category: "frozen", weight: 1.5, weightUnit: "kg" },
  { name: "HB Vanilla Ice Cream 900ml", price: 3.99, brand: "HB", category: "frozen", weight: 900, weightUnit: "ml" },
  { name: "Ben & Jerrys Cookie Dough 465ml", price: 5.99, brand: "Ben & Jerrys", category: "frozen", weight: 465, weightUnit: "ml" },
  { name: "Tesco Frozen Garden Peas 900g", price: 1.49, brand: "Tesco", category: "frozen", weight: 900, weightUnit: "g" },
  { name: "Tesco Frozen Mixed Vegetables 1kg", price: 1.69, brand: "Tesco", category: "frozen", weight: 1, weightUnit: "kg" },
  { name: "Tesco Frozen Chicken Goujons 400g", price: 2.99, brand: "Tesco", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Tesco Frozen Lasagne 400g", price: 2.29, brand: "Tesco", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Tesco Frozen Shepherd Pie 400g", price: 2.19, brand: "Tesco", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Tesco Frozen Waffles 12 Pack", price: 1.79, brand: "Tesco", category: "frozen", weight: 12, weightUnit: "units" },
  { name: "Tesco Frozen Prawns 250g", price: 4.49, brand: "Tesco", category: "frozen", weight: 250, weightUnit: "g" },
  { name: "Tesco Frozen Battered Cod 400g", price: 3.49, brand: "Tesco", category: "frozen", weight: 400, weightUnit: "g" },
  // ── snacks & sweets (15) ──
  { name: "Cadbury Dairy Milk 200g", price: 2.49, brand: "Cadbury", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Cadbury Bournville Dark Chocolate 180g", price: 2.29, brand: "Cadbury", category: "snacks & sweets", weight: 180, weightUnit: "g" },
  { name: "Tesco Dark Chocolate 100g", price: 1.19, brand: "Tesco", category: "snacks & sweets", weight: 100, weightUnit: "g" },
  { name: "Tesco Milk Chocolate Bar 200g", price: 1.49, brand: "Tesco", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tayto Cheese & Onion Multipack 12 Pack", price: 4.49, brand: "Tayto", category: "snacks & sweets", weight: 12, weightUnit: "units" },
  { name: "Pringles Original 165g", price: 2.99, brand: "Pringles", category: "snacks & sweets", weight: 165, weightUnit: "g" },
  { name: "Tesco Digestive Biscuits 400g", price: 1.15, brand: "Tesco", category: "snacks & sweets", weight: 400, weightUnit: "g" },
  { name: "McVities Chocolate Digestives 300g", price: 2.19, brand: "McVities", category: "snacks & sweets", weight: 300, weightUnit: "g" },
  { name: "Tesco Salted Cashews 200g", price: 2.79, brand: "Tesco", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tesco Mixed Nuts 200g", price: 2.49, brand: "Tesco", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tesco Sweet Microwave Popcorn 3 Pack", price: 1.29, brand: "Tesco", category: "snacks & sweets", weight: 3, weightUnit: "units" },
  { name: "Haribo Goldbears 160g", price: 1.49, brand: "Haribo", category: "snacks & sweets", weight: 160, weightUnit: "g" },
  { name: "Tesco Chocolate Chip Cookies 200g", price: 1.29, brand: "Tesco", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "KitKat 4 Finger 41.5g", price: 0.99, brand: "KitKat", category: "snacks & sweets", weight: 41.5, weightUnit: "g" },
  { name: "Tesco Trail Mix 200g", price: 2.29, brand: "Tesco", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  // ── household (15) ──
  { name: "Tesco Kitchen Roll 2 Pack", price: 1.99, brand: "Tesco", category: "household", weight: 2, weightUnit: "units" },
  { name: "Tesco Toilet Roll 9 Pack", price: 3.79, brand: "Tesco", category: "household", weight: 9, weightUnit: "units" },
  { name: "Tesco Toilet Roll 4 Pack", price: 1.89, brand: "Tesco", category: "household", weight: 4, weightUnit: "units" },
  { name: "Fairy Washing Up Liquid 500ml", price: 2.49, brand: "Fairy", category: "household", weight: 500, weightUnit: "ml" },
  { name: "Persil Laundry Detergent 1.1L", price: 7.99, brand: "Persil", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Tesco Laundry Detergent 1.1L", price: 3.99, brand: "Tesco", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Tesco Bin Bags 30 Pack", price: 2.49, brand: "Tesco", category: "household", weight: 30, weightUnit: "units" },
  { name: "Tesco Dishwasher Tablets 30 Pack", price: 3.99, brand: "Tesco", category: "household", weight: 30, weightUnit: "units" },
  { name: "Finish Dishwasher Tablets 50 Pack", price: 8.99, brand: "Finish", category: "household", weight: 50, weightUnit: "units" },
  { name: "Tesco Antibacterial Surface Spray 750ml", price: 1.49, brand: "Tesco", category: "household", weight: 750, weightUnit: "ml" },
  { name: "Tesco Hand Soap 250ml", price: 0.79, brand: "Tesco", category: "household", weight: 250, weightUnit: "ml" },
  { name: "Tesco Fabric Conditioner 1.5L", price: 2.49, brand: "Tesco", category: "household", weight: 1.5, weightUnit: "l" },
  { name: "Tesco Cling Film 30m", price: 1.29, brand: "Tesco", category: "household", weight: 30, weightUnit: "units" },
  { name: "Tesco Tin Foil 10m", price: 1.49, brand: "Tesco", category: "household", weight: 10, weightUnit: "units" },
  { name: "Tesco Sponge Scourers 4 Pack", price: 0.99, brand: "Tesco", category: "household", weight: 4, weightUnit: "units" },
  // ── personal care (10) ──
  { name: "Tesco Shampoo 400ml", price: 1.49, brand: "Tesco", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Head & Shoulders Shampoo 250ml", price: 3.99, brand: "Head & Shoulders", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Tesco Shower Gel 400ml", price: 1.29, brand: "Tesco", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Dove Shower Gel 250ml", price: 2.99, brand: "Dove", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Colgate Total Toothpaste 75ml", price: 2.49, brand: "Colgate", category: "personal care", weight: 75, weightUnit: "ml" },
  { name: "Tesco Toothpaste 100ml", price: 0.89, brand: "Tesco", category: "personal care", weight: 100, weightUnit: "ml" },
  { name: "Sure Antiperspirant 150ml", price: 2.99, brand: "Sure", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Tesco Deodorant 150ml", price: 1.29, brand: "Tesco", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Tesco Facial Tissues 100 Pack", price: 0.99, brand: "Tesco", category: "personal care", weight: 100, weightUnit: "units" },
  { name: "Tesco Cotton Pads 100 Pack", price: 1.19, brand: "Tesco", category: "personal care", weight: 100, weightUnit: "units" },
  // ── baby (5) ──
  { name: "Pampers Baby Dry Nappies Size 4 58 Pack", price: 12.99, brand: "Pampers", category: "baby", weight: 58, weightUnit: "units" },
  { name: "Tesco Nappies Size 4 50 Pack", price: 7.99, brand: "Tesco", category: "baby", weight: 50, weightUnit: "units" },
  { name: "WaterWipes Baby Wipes 60 Pack", price: 3.49, brand: "WaterWipes", category: "baby", weight: 60, weightUnit: "units" },
  { name: "Cow & Gate Stage 1 Baby Food 125g", price: 1.29, brand: "Cow & Gate", category: "baby", weight: 125, weightUnit: "g" },
  { name: "Ella's Kitchen Organic Baby Food 120g", price: 1.79, brand: "Ella's Kitchen", category: "baby", weight: 120, weightUnit: "g" },
];

const DUNNES_PRODUCTS: ScrapedProduct[] = [
  // ── dairy & eggs (20) ──
  { name: "Dunnes Irish Whole Milk 2L", price: 1.90, brand: "Dunnes", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Dunnes Low Fat Milk 2L", price: 1.85, brand: "Dunnes", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Dunnes Whole Milk 1L", price: 1.20, brand: "Dunnes", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Dunnes Skimmed Milk 1L", price: 1.15, brand: "Dunnes", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Kerrygold Pure Irish Butter 227g", price: 2.79, brand: "Kerrygold", category: "dairy & eggs", weight: 227, weightUnit: "g" },
  { name: "Dunnes Spreadable Butter 500g", price: 3.45, brand: "Dunnes", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Dunnes Mild Cheddar Cheese 200g", price: 1.99, brand: "Dunnes", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Dunnes Mature Cheddar Cheese 200g", price: 2.29, brand: "Dunnes", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Dunnes Grated Mozzarella 250g", price: 1.65, brand: "Dunnes", category: "dairy & eggs", weight: 250, weightUnit: "g" },
  { name: "Glenisk Organic Natural Yoghurt 500g", price: 2.39, brand: "Glenisk", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Dunnes Greek Style Yoghurt 500g", price: 1.55, brand: "Dunnes", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Dunnes Natural Yoghurt 500g", price: 1.05, brand: "Dunnes", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Dunnes Free Range Eggs 10 Pack", price: 3.09, brand: "Dunnes", category: "dairy & eggs", weight: 10, weightUnit: "units" },
  { name: "Dunnes Free Range Eggs 6 Pack", price: 1.99, brand: "Dunnes", category: "dairy & eggs", weight: 6, weightUnit: "units" },
  { name: "Dunnes Fresh Cream 250ml", price: 1.35, brand: "Dunnes", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Dunnes Double Cream 250ml", price: 1.55, brand: "Dunnes", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Dunnes Cottage Cheese 300g", price: 1.79, brand: "Dunnes", category: "dairy & eggs", weight: 300, weightUnit: "g" },
  { name: "Dunnes Cream Cheese 200g", price: 1.39, brand: "Dunnes", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Dunnes Sliced Cheese 150g", price: 1.59, brand: "Dunnes", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  { name: "Dunnes Parmesan Wedge 150g", price: 3.19, brand: "Dunnes", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  // ── meat & poultry (15) ──
  { name: "Dunnes Irish Chicken Breast Fillets 360g", price: 4.59, brand: "Dunnes", category: "meat & poultry", weight: 360, weightUnit: "g" },
  { name: "Dunnes Irish Chicken Thighs 500g", price: 3.39, brand: "Dunnes", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Dunnes Irish Chicken Drumsticks 500g", price: 2.79, brand: "Dunnes", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Dunnes Whole Irish Chicken 1.5kg", price: 5.89, brand: "Dunnes", category: "meat & poultry", weight: 1.5, weightUnit: "kg" },
  { name: "Dunnes Irish Beef Mince 400g", price: 4.09, brand: "Dunnes", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Dunnes Irish Beef Mince 750g", price: 6.59, brand: "Dunnes", category: "meat & poultry", weight: 750, weightUnit: "g" },
  { name: "Dunnes Irish Beef Steak 250g", price: 5.39, brand: "Dunnes", category: "meat & poultry", weight: 250, weightUnit: "g" },
  { name: "Dunnes Streaky Bacon Rashers 200g", price: 2.39, brand: "Dunnes", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Dunnes Back Bacon Rashers 200g", price: 2.89, brand: "Dunnes", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Dunnes Irish Pork Sausages 454g", price: 2.55, brand: "Dunnes", category: "meat & poultry", weight: 454, weightUnit: "g" },
  { name: "Dunnes Cooked Ham Slices 200g", price: 2.79, brand: "Dunnes", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Dunnes Smoked Salmon 100g", price: 4.19, brand: "Dunnes", category: "meat & poultry", weight: 100, weightUnit: "g" },
  { name: "Dunnes Fresh Salmon Fillets 260g", price: 5.39, brand: "Dunnes", category: "meat & poultry", weight: 260, weightUnit: "g" },
  { name: "Dunnes Irish Turkey Mince 400g", price: 3.89, brand: "Dunnes", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Dunnes Lamb Leg Steak 200g", price: 4.89, brand: "Dunnes", category: "meat & poultry", weight: 200, weightUnit: "g" },
  // ── fruits & vegetables (20) ──
  { name: "Dunnes Bananas 5 Pack", price: 1.05, brand: "Dunnes", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Dunnes Royal Gala Apples 6 Pack", price: 1.89, brand: "Dunnes", category: "fruits & vegetables", weight: 6, weightUnit: "units" },
  { name: "Dunnes Broccoli Head", price: 1.05, brand: "Dunnes", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Dunnes Carrots 1kg", price: 0.85, brand: "Dunnes", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Dunnes Rooster Potatoes 2.5kg", price: 2.59, brand: "Dunnes", category: "fruits & vegetables", weight: 2.5, weightUnit: "kg" },
  { name: "Dunnes White Potatoes 2kg", price: 1.85, brand: "Dunnes", category: "fruits & vegetables", weight: 2, weightUnit: "kg" },
  { name: "Dunnes Iceberg Lettuce", price: 0.95, brand: "Dunnes", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Dunnes Vine Tomatoes 450g", price: 1.49, brand: "Dunnes", category: "fruits & vegetables", weight: 450, weightUnit: "g" },
  { name: "Dunnes Brown Onions 1kg", price: 0.95, brand: "Dunnes", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Dunnes Closed Cup Mushrooms 250g", price: 1.19, brand: "Dunnes", category: "fruits & vegetables", weight: 250, weightUnit: "g" },
  { name: "Dunnes Red Peppers 3 Pack", price: 1.69, brand: "Dunnes", category: "fruits & vegetables", weight: 3, weightUnit: "units" },
  { name: "Dunnes Avocados 2 Pack", price: 1.89, brand: "Dunnes", category: "fruits & vegetables", weight: 2, weightUnit: "units" },
  { name: "Dunnes Strawberries 400g", price: 2.89, brand: "Dunnes", category: "fruits & vegetables", weight: 400, weightUnit: "g" },
  { name: "Dunnes Blueberries 150g", price: 2.39, brand: "Dunnes", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Dunnes Raspberries 150g", price: 2.89, brand: "Dunnes", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Dunnes Cucumber", price: 0.75, brand: "Dunnes", category: "fruits & vegetables", weight: 1, weightUnit: "units" },
  { name: "Dunnes Baby Spinach 100g", price: 1.59, brand: "Dunnes", category: "fruits & vegetables", weight: 100, weightUnit: "g" },
  { name: "Dunnes Courgettes 500g", price: 1.25, brand: "Dunnes", category: "fruits & vegetables", weight: 500, weightUnit: "g" },
  { name: "Dunnes Lemons 5 Pack", price: 1.45, brand: "Dunnes", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Dunnes Mixed Salad Bag 120g", price: 1.49, brand: "Dunnes", category: "fruits & vegetables", weight: 120, weightUnit: "g" },
  // ── bakery (12) ──
  { name: "Dunnes White Sliced Pan 800g", price: 1.29, brand: "Dunnes", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Dunnes Wholemeal Sliced Pan 800g", price: 1.39, brand: "Dunnes", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Family Pan 800g", price: 2.05, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Wholemeal Bread 800g", price: 2.15, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Dunnes 4 Butter Croissants", price: 1.55, brand: "Dunnes", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Dunnes Sourdough Bread 500g", price: 1.89, brand: "Dunnes", category: "bakery", weight: 500, weightUnit: "g" },
  { name: "Dunnes Soft White Rolls 6 Pack", price: 1.19, brand: "Dunnes", category: "bakery", weight: 6, weightUnit: "units" },
  { name: "Dunnes Tortilla Wraps 8 Pack", price: 1.49, brand: "Dunnes", category: "bakery", weight: 8, weightUnit: "units" },
  { name: "Dunnes Scones 4 Pack", price: 1.39, brand: "Dunnes", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Dunnes Bagels 5 Pack", price: 1.29, brand: "Dunnes", category: "bakery", weight: 5, weightUnit: "units" },
  { name: "Dunnes Garlic Bread Baguette 270g", price: 1.39, brand: "Dunnes", category: "bakery", weight: 270, weightUnit: "g" },
  { name: "Johnston Mooney & OBrien Batch Loaf 800g", price: 2.25, brand: "Johnston Mooney", category: "bakery", weight: 800, weightUnit: "g" },
  // ── drinks (20) ──
  { name: "Dunnes Still Water 2L", price: 0.49, brand: "Dunnes", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Dunnes Still Water 500ml", price: 0.35, brand: "Dunnes", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Dunnes Orange Juice 1L", price: 1.75, brand: "Dunnes", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Dunnes Apple Juice 1L", price: 1.55, brand: "Dunnes", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Barry's Gold Blend Tea 80s", price: 4.19, brand: "Barry's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Lyon's Original Tea 80s", price: 3.89, brand: "Lyon's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Nescafé Original Instant Coffee 200g", price: 6.89, brand: "Nescafé", category: "drinks", weight: 200, weightUnit: "g" },
  { name: "Coca-Cola 2L", price: 2.79, brand: "Coca-Cola", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Coca-Cola 6 Pack 330ml", price: 4.89, brand: "Coca-Cola", category: "drinks", weight: 6, weightUnit: "units" },
  { name: "Dunnes Cola 2L", price: 0.89, brand: "Dunnes", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Club Orange 2L", price: 2.45, brand: "Club", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Lucozade Energy Original 1L", price: 2.65, brand: "Lucozade", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Monster Energy 500ml", price: 1.95, brand: "Monster", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Dunnes Oat Milk 1L", price: 1.75, brand: "Dunnes", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Dunnes Almond Milk 1L", price: 1.65, brand: "Dunnes", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Dunnes Sparkling Water 2L", price: 0.49, brand: "Dunnes", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Robinsons Orange Squash 1L", price: 2.45, brand: "Robinsons", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tropicana Orange Juice 950ml", price: 3.39, brand: "Tropicana", category: "drinks", weight: 950, weightUnit: "ml" },
  { name: "Dunnes Cranberry Juice 1L", price: 1.79, brand: "Dunnes", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Ballygowan Still Water 2L", price: 1.25, brand: "Ballygowan", category: "drinks", weight: 2, weightUnit: "l" },
  // ── frozen (15) ──
  { name: "Birds Eye Fish Fingers 450g", price: 3.89, brand: "Birds Eye", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Dunnes Fish Fingers 450g", price: 2.69, brand: "Dunnes", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Dunnes Frozen Pizza Margherita 300g", price: 1.79, brand: "Dunnes", category: "frozen", weight: 300, weightUnit: "g" },
  { name: "Chicago Town Pepperoni Pizza 400g", price: 3.39, brand: "Chicago Town", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Dunnes Frozen Chips 1.5kg", price: 2.09, brand: "Dunnes", category: "frozen", weight: 1.5, weightUnit: "kg" },
  { name: "HB Vanilla Ice Cream 900ml", price: 3.89, brand: "HB", category: "frozen", weight: 900, weightUnit: "ml" },
  { name: "Ben & Jerrys Cookie Dough 465ml", price: 5.89, brand: "Ben & Jerrys", category: "frozen", weight: 465, weightUnit: "ml" },
  { name: "Dunnes Frozen Garden Peas 900g", price: 1.39, brand: "Dunnes", category: "frozen", weight: 900, weightUnit: "g" },
  { name: "Dunnes Frozen Mixed Vegetables 1kg", price: 1.59, brand: "Dunnes", category: "frozen", weight: 1, weightUnit: "kg" },
  { name: "Dunnes Frozen Chicken Goujons 400g", price: 2.89, brand: "Dunnes", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Dunnes Frozen Lasagne 400g", price: 2.19, brand: "Dunnes", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Dunnes Frozen Shepherd Pie 400g", price: 2.09, brand: "Dunnes", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Dunnes Frozen Waffles 12 Pack", price: 1.69, brand: "Dunnes", category: "frozen", weight: 12, weightUnit: "units" },
  { name: "Dunnes Frozen Prawns 250g", price: 4.39, brand: "Dunnes", category: "frozen", weight: 250, weightUnit: "g" },
  { name: "Dunnes Frozen Battered Cod 400g", price: 3.39, brand: "Dunnes", category: "frozen", weight: 400, weightUnit: "g" },
  // ── snacks & sweets (15) ──
  { name: "Cadbury Dairy Milk 200g", price: 2.39, brand: "Cadbury", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Cadbury Bournville Dark Chocolate 180g", price: 2.19, brand: "Cadbury", category: "snacks & sweets", weight: 180, weightUnit: "g" },
  { name: "Dunnes Dark Chocolate 100g", price: 1.09, brand: "Dunnes", category: "snacks & sweets", weight: 100, weightUnit: "g" },
  { name: "Dunnes Milk Chocolate Bar 200g", price: 1.39, brand: "Dunnes", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tayto Cheese & Onion Multipack 12 Pack", price: 4.39, brand: "Tayto", category: "snacks & sweets", weight: 12, weightUnit: "units" },
  { name: "Pringles Original 165g", price: 2.89, brand: "Pringles", category: "snacks & sweets", weight: 165, weightUnit: "g" },
  { name: "Dunnes Digestive Biscuits 400g", price: 1.09, brand: "Dunnes", category: "snacks & sweets", weight: 400, weightUnit: "g" },
  { name: "McVities Chocolate Digestives 300g", price: 2.09, brand: "McVities", category: "snacks & sweets", weight: 300, weightUnit: "g" },
  { name: "Dunnes Salted Cashews 200g", price: 2.69, brand: "Dunnes", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Dunnes Mixed Nuts 200g", price: 2.39, brand: "Dunnes", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Dunnes Sweet Microwave Popcorn 3 Pack", price: 1.19, brand: "Dunnes", category: "snacks & sweets", weight: 3, weightUnit: "units" },
  { name: "Haribo Goldbears 160g", price: 1.45, brand: "Haribo", category: "snacks & sweets", weight: 160, weightUnit: "g" },
  { name: "Dunnes Chocolate Chip Cookies 200g", price: 1.19, brand: "Dunnes", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "KitKat 4 Finger 41.5g", price: 0.95, brand: "KitKat", category: "snacks & sweets", weight: 41.5, weightUnit: "g" },
  { name: "Dunnes Trail Mix 200g", price: 2.19, brand: "Dunnes", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  // ── household (15) ──
  { name: "Dunnes Kitchen Roll 2 Pack", price: 1.89, brand: "Dunnes", category: "household", weight: 2, weightUnit: "units" },
  { name: "Dunnes Toilet Roll 9 Pack", price: 3.59, brand: "Dunnes", category: "household", weight: 9, weightUnit: "units" },
  { name: "Dunnes Toilet Roll 4 Pack", price: 1.79, brand: "Dunnes", category: "household", weight: 4, weightUnit: "units" },
  { name: "Fairy Washing Up Liquid 500ml", price: 2.39, brand: "Fairy", category: "household", weight: 500, weightUnit: "ml" },
  { name: "Persil Laundry Detergent 1.1L", price: 7.79, brand: "Persil", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Dunnes Laundry Detergent 1.1L", price: 3.89, brand: "Dunnes", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Dunnes Bin Bags 30 Pack", price: 2.39, brand: "Dunnes", category: "household", weight: 30, weightUnit: "units" },
  { name: "Dunnes Dishwasher Tablets 30 Pack", price: 3.89, brand: "Dunnes", category: "household", weight: 30, weightUnit: "units" },
  { name: "Finish Dishwasher Tablets 50 Pack", price: 8.89, brand: "Finish", category: "household", weight: 50, weightUnit: "units" },
  { name: "Dunnes Antibacterial Surface Spray 750ml", price: 1.39, brand: "Dunnes", category: "household", weight: 750, weightUnit: "ml" },
  { name: "Dunnes Hand Soap 250ml", price: 0.75, brand: "Dunnes", category: "household", weight: 250, weightUnit: "ml" },
  { name: "Dunnes Fabric Conditioner 1.5L", price: 2.39, brand: "Dunnes", category: "household", weight: 1.5, weightUnit: "l" },
  { name: "Dunnes Cling Film 30m", price: 1.19, brand: "Dunnes", category: "household", weight: 30, weightUnit: "units" },
  { name: "Dunnes Tin Foil 10m", price: 1.39, brand: "Dunnes", category: "household", weight: 10, weightUnit: "units" },
  { name: "Dunnes Sponge Scourers 4 Pack", price: 0.89, brand: "Dunnes", category: "household", weight: 4, weightUnit: "units" },
  // ── personal care (10) ──
  { name: "Dunnes Shampoo 400ml", price: 1.39, brand: "Dunnes", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Head & Shoulders Shampoo 250ml", price: 3.89, brand: "Head & Shoulders", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Dunnes Shower Gel 400ml", price: 1.19, brand: "Dunnes", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Dove Shower Gel 250ml", price: 2.89, brand: "Dove", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Colgate Total Toothpaste 75ml", price: 2.39, brand: "Colgate", category: "personal care", weight: 75, weightUnit: "ml" },
  { name: "Dunnes Toothpaste 100ml", price: 0.85, brand: "Dunnes", category: "personal care", weight: 100, weightUnit: "ml" },
  { name: "Sure Antiperspirant 150ml", price: 2.89, brand: "Sure", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Dunnes Deodorant 150ml", price: 1.19, brand: "Dunnes", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Dunnes Facial Tissues 100 Pack", price: 0.89, brand: "Dunnes", category: "personal care", weight: 100, weightUnit: "units" },
  { name: "Dunnes Cotton Pads 100 Pack", price: 1.09, brand: "Dunnes", category: "personal care", weight: 100, weightUnit: "units" },
  // ── baby (5) ──
  { name: "Pampers Baby Dry Nappies Size 4 58 Pack", price: 12.89, brand: "Pampers", category: "baby", weight: 58, weightUnit: "units" },
  { name: "Dunnes Nappies Size 4 50 Pack", price: 7.49, brand: "Dunnes", category: "baby", weight: 50, weightUnit: "units" },
  { name: "WaterWipes Baby Wipes 60 Pack", price: 3.39, brand: "WaterWipes", category: "baby", weight: 60, weightUnit: "units" },
  { name: "Cow & Gate Stage 1 Baby Food 125g", price: 1.25, brand: "Cow & Gate", category: "baby", weight: 125, weightUnit: "g" },
  { name: "Ella's Kitchen Organic Baby Food 120g", price: 1.75, brand: "Ella's Kitchen", category: "baby", weight: 120, weightUnit: "g" },
];

const SUPERVALU_PRODUCTS: ScrapedProduct[] = [
  // ── dairy & eggs (20) ──
  { name: "SuperValu Irish Whole Milk 2L", price: 1.99, brand: "SuperValu", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "SuperValu Low Fat Milk 2L", price: 1.95, brand: "SuperValu", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "SuperValu Whole Milk 1L", price: 1.29, brand: "SuperValu", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "SuperValu Skimmed Milk 1L", price: 1.25, brand: "SuperValu", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Kerrygold Pure Irish Butter 227g", price: 2.95, brand: "Kerrygold", category: "dairy & eggs", weight: 227, weightUnit: "g" },
  { name: "SuperValu Spreadable Butter 500g", price: 3.65, brand: "SuperValu", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "SuperValu Mild Cheddar Cheese 200g", price: 2.25, brand: "SuperValu", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "SuperValu Mature Cheddar Cheese 200g", price: 2.55, brand: "SuperValu", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "SuperValu Grated Mozzarella 250g", price: 1.85, brand: "SuperValu", category: "dairy & eggs", weight: 250, weightUnit: "g" },
  { name: "Glenisk Organic Natural Yoghurt 500g", price: 2.55, brand: "Glenisk", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "SuperValu Greek Style Yoghurt 500g", price: 1.65, brand: "SuperValu", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "SuperValu Natural Yoghurt 500g", price: 1.15, brand: "SuperValu", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "SuperValu Free Range Eggs 10 Pack", price: 3.29, brand: "SuperValu", category: "dairy & eggs", weight: 10, weightUnit: "units" },
  { name: "SuperValu Free Range Eggs 6 Pack", price: 2.15, brand: "SuperValu", category: "dairy & eggs", weight: 6, weightUnit: "units" },
  { name: "SuperValu Fresh Cream 250ml", price: 1.45, brand: "SuperValu", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "SuperValu Double Cream 250ml", price: 1.65, brand: "SuperValu", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "SuperValu Cottage Cheese 300g", price: 1.95, brand: "SuperValu", category: "dairy & eggs", weight: 300, weightUnit: "g" },
  { name: "SuperValu Cream Cheese 200g", price: 1.55, brand: "SuperValu", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "SuperValu Sliced Cheese 150g", price: 1.75, brand: "SuperValu", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  { name: "SuperValu Parmesan Wedge 150g", price: 3.39, brand: "SuperValu", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  // ── meat & poultry (15) ──
  { name: "SuperValu Irish Chicken Breast Fillets 360g", price: 4.79, brand: "SuperValu", category: "meat & poultry", weight: 360, weightUnit: "g" },
  { name: "SuperValu Irish Chicken Thighs 500g", price: 3.55, brand: "SuperValu", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "SuperValu Irish Chicken Drumsticks 500g", price: 2.99, brand: "SuperValu", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "SuperValu Whole Irish Chicken 1.5kg", price: 6.19, brand: "SuperValu", category: "meat & poultry", weight: 1.5, weightUnit: "kg" },
  { name: "SuperValu Irish Beef Mince 400g", price: 4.29, brand: "SuperValu", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "SuperValu Irish Beef Mince 750g", price: 6.89, brand: "SuperValu", category: "meat & poultry", weight: 750, weightUnit: "g" },
  { name: "SuperValu Irish Beef Steak 250g", price: 5.69, brand: "SuperValu", category: "meat & poultry", weight: 250, weightUnit: "g" },
  { name: "SuperValu Streaky Bacon Rashers 200g", price: 2.55, brand: "SuperValu", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "SuperValu Back Bacon Rashers 200g", price: 3.09, brand: "SuperValu", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "SuperValu Irish Pork Sausages 454g", price: 2.75, brand: "SuperValu", category: "meat & poultry", weight: 454, weightUnit: "g" },
  { name: "SuperValu Cooked Ham Slices 200g", price: 2.99, brand: "SuperValu", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "SuperValu Smoked Salmon 100g", price: 4.39, brand: "SuperValu", category: "meat & poultry", weight: 100, weightUnit: "g" },
  { name: "SuperValu Fresh Salmon Fillets 260g", price: 5.59, brand: "SuperValu", category: "meat & poultry", weight: 260, weightUnit: "g" },
  { name: "SuperValu Irish Turkey Mince 400g", price: 4.09, brand: "SuperValu", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "SuperValu Lamb Leg Steak 200g", price: 5.09, brand: "SuperValu", category: "meat & poultry", weight: 200, weightUnit: "g" },
  // ── fruits & vegetables (20) ──
  { name: "SuperValu Bananas 5 Pack", price: 1.15, brand: "SuperValu", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "SuperValu Royal Gala Apples 6 Pack", price: 2.09, brand: "SuperValu", category: "fruits & vegetables", weight: 6, weightUnit: "units" },
  { name: "SuperValu Broccoli Head", price: 1.15, brand: "SuperValu", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "SuperValu Carrots 1kg", price: 0.95, brand: "SuperValu", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "SuperValu Rooster Potatoes 2.5kg", price: 2.79, brand: "SuperValu", category: "fruits & vegetables", weight: 2.5, weightUnit: "kg" },
  { name: "SuperValu White Potatoes 2kg", price: 1.95, brand: "SuperValu", category: "fruits & vegetables", weight: 2, weightUnit: "kg" },
  { name: "SuperValu Iceberg Lettuce", price: 1.05, brand: "SuperValu", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "SuperValu Vine Tomatoes 450g", price: 1.65, brand: "SuperValu", category: "fruits & vegetables", weight: 450, weightUnit: "g" },
  { name: "SuperValu Brown Onions 1kg", price: 1.05, brand: "SuperValu", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "SuperValu Closed Cup Mushrooms 250g", price: 1.35, brand: "SuperValu", category: "fruits & vegetables", weight: 250, weightUnit: "g" },
  { name: "SuperValu Red Peppers 3 Pack", price: 1.89, brand: "SuperValu", category: "fruits & vegetables", weight: 3, weightUnit: "units" },
  { name: "SuperValu Avocados 2 Pack", price: 2.09, brand: "SuperValu", category: "fruits & vegetables", weight: 2, weightUnit: "units" },
  { name: "SuperValu Strawberries 400g", price: 3.09, brand: "SuperValu", category: "fruits & vegetables", weight: 400, weightUnit: "g" },
  { name: "SuperValu Blueberries 150g", price: 2.59, brand: "SuperValu", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "SuperValu Raspberries 150g", price: 3.09, brand: "SuperValu", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "SuperValu Cucumber", price: 0.85, brand: "SuperValu", category: "fruits & vegetables", weight: 1, weightUnit: "units" },
  { name: "SuperValu Baby Spinach 100g", price: 1.79, brand: "SuperValu", category: "fruits & vegetables", weight: 100, weightUnit: "g" },
  { name: "SuperValu Courgettes 500g", price: 1.39, brand: "SuperValu", category: "fruits & vegetables", weight: 500, weightUnit: "g" },
  { name: "SuperValu Lemons 5 Pack", price: 1.55, brand: "SuperValu", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "SuperValu Mixed Salad Bag 120g", price: 1.69, brand: "SuperValu", category: "fruits & vegetables", weight: 120, weightUnit: "g" },
  // ── bakery (12) ──
  { name: "SuperValu White Sliced Pan 800g", price: 1.39, brand: "SuperValu", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "SuperValu Wholemeal Sliced Pan 800g", price: 1.49, brand: "SuperValu", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Family Pan 800g", price: 2.15, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Wholemeal Bread 800g", price: 2.25, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "SuperValu 4 Butter Croissants", price: 1.75, brand: "SuperValu", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "SuperValu Sourdough Bread 500g", price: 2.09, brand: "SuperValu", category: "bakery", weight: 500, weightUnit: "g" },
  { name: "SuperValu Soft White Rolls 6 Pack", price: 1.35, brand: "SuperValu", category: "bakery", weight: 6, weightUnit: "units" },
  { name: "SuperValu Tortilla Wraps 8 Pack", price: 1.65, brand: "SuperValu", category: "bakery", weight: 8, weightUnit: "units" },
  { name: "SuperValu Scones 4 Pack", price: 1.55, brand: "SuperValu", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "SuperValu Bagels 5 Pack", price: 1.49, brand: "SuperValu", category: "bakery", weight: 5, weightUnit: "units" },
  { name: "SuperValu Garlic Bread Baguette 270g", price: 1.55, brand: "SuperValu", category: "bakery", weight: 270, weightUnit: "g" },
  { name: "Johnston Mooney & OBrien Batch Loaf 800g", price: 2.35, brand: "Johnston Mooney", category: "bakery", weight: 800, weightUnit: "g" },
  // ── drinks (20) ──
  { name: "SuperValu Still Water 2L", price: 0.59, brand: "SuperValu", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "SuperValu Still Water 500ml", price: 0.42, brand: "SuperValu", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "SuperValu Orange Juice 1L", price: 1.89, brand: "SuperValu", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "SuperValu Apple Juice 1L", price: 1.65, brand: "SuperValu", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Barry's Gold Blend Tea 80s", price: 4.39, brand: "Barry's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Lyon's Original Tea 80s", price: 4.09, brand: "Lyon's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Nescafé Original Instant Coffee 200g", price: 7.19, brand: "Nescafé", category: "drinks", weight: 200, weightUnit: "g" },
  { name: "Coca-Cola 2L", price: 2.89, brand: "Coca-Cola", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Coca-Cola 6 Pack 330ml", price: 5.09, brand: "Coca-Cola", category: "drinks", weight: 6, weightUnit: "units" },
  { name: "SuperValu Cola 2L", price: 0.99, brand: "SuperValu", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Club Orange 2L", price: 2.55, brand: "Club", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Lucozade Energy Original 1L", price: 2.75, brand: "Lucozade", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Monster Energy 500ml", price: 2.05, brand: "Monster", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "SuperValu Oat Milk 1L", price: 1.85, brand: "SuperValu", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "SuperValu Almond Milk 1L", price: 1.79, brand: "SuperValu", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "SuperValu Sparkling Water 2L", price: 0.59, brand: "SuperValu", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Robinsons Orange Squash 1L", price: 2.55, brand: "Robinsons", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tropicana Orange Juice 950ml", price: 3.59, brand: "Tropicana", category: "drinks", weight: 950, weightUnit: "ml" },
  { name: "SuperValu Cranberry Juice 1L", price: 1.95, brand: "SuperValu", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Ballygowan Still Water 2L", price: 1.35, brand: "Ballygowan", category: "drinks", weight: 2, weightUnit: "l" },
  // ── frozen (15) ──
  { name: "Birds Eye Fish Fingers 450g", price: 4.09, brand: "Birds Eye", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "SuperValu Fish Fingers 450g", price: 2.79, brand: "SuperValu", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "SuperValu Frozen Pizza Margherita 300g", price: 1.95, brand: "SuperValu", category: "frozen", weight: 300, weightUnit: "g" },
  { name: "Chicago Town Pepperoni Pizza 400g", price: 3.59, brand: "Chicago Town", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "SuperValu Frozen Chips 1.5kg", price: 2.29, brand: "SuperValu", category: "frozen", weight: 1.5, weightUnit: "kg" },
  { name: "HB Vanilla Ice Cream 900ml", price: 4.09, brand: "HB", category: "frozen", weight: 900, weightUnit: "ml" },
  { name: "Ben & Jerrys Cookie Dough 465ml", price: 6.09, brand: "Ben & Jerrys", category: "frozen", weight: 465, weightUnit: "ml" },
  { name: "SuperValu Frozen Garden Peas 900g", price: 1.55, brand: "SuperValu", category: "frozen", weight: 900, weightUnit: "g" },
  { name: "SuperValu Frozen Mixed Vegetables 1kg", price: 1.79, brand: "SuperValu", category: "frozen", weight: 1, weightUnit: "kg" },
  { name: "SuperValu Frozen Chicken Goujons 400g", price: 3.09, brand: "SuperValu", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "SuperValu Frozen Lasagne 400g", price: 2.39, brand: "SuperValu", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "SuperValu Frozen Shepherd Pie 400g", price: 2.29, brand: "SuperValu", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "SuperValu Frozen Waffles 12 Pack", price: 1.89, brand: "SuperValu", category: "frozen", weight: 12, weightUnit: "units" },
  { name: "SuperValu Frozen Prawns 250g", price: 4.59, brand: "SuperValu", category: "frozen", weight: 250, weightUnit: "g" },
  { name: "SuperValu Frozen Battered Cod 400g", price: 3.59, brand: "SuperValu", category: "frozen", weight: 400, weightUnit: "g" },
  // ── snacks & sweets (15) ──
  { name: "Cadbury Dairy Milk 200g", price: 2.59, brand: "Cadbury", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Cadbury Bournville Dark Chocolate 180g", price: 2.39, brand: "Cadbury", category: "snacks & sweets", weight: 180, weightUnit: "g" },
  { name: "SuperValu Dark Chocolate 100g", price: 1.25, brand: "SuperValu", category: "snacks & sweets", weight: 100, weightUnit: "g" },
  { name: "SuperValu Milk Chocolate Bar 200g", price: 1.59, brand: "SuperValu", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tayto Cheese & Onion Multipack 12 Pack", price: 4.59, brand: "Tayto", category: "snacks & sweets", weight: 12, weightUnit: "units" },
  { name: "Pringles Original 165g", price: 3.09, brand: "Pringles", category: "snacks & sweets", weight: 165, weightUnit: "g" },
  { name: "SuperValu Digestive Biscuits 400g", price: 1.19, brand: "SuperValu", category: "snacks & sweets", weight: 400, weightUnit: "g" },
  { name: "McVities Chocolate Digestives 300g", price: 2.29, brand: "McVities", category: "snacks & sweets", weight: 300, weightUnit: "g" },
  { name: "SuperValu Salted Cashews 200g", price: 2.89, brand: "SuperValu", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "SuperValu Mixed Nuts 200g", price: 2.59, brand: "SuperValu", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "SuperValu Sweet Microwave Popcorn 3 Pack", price: 1.35, brand: "SuperValu", category: "snacks & sweets", weight: 3, weightUnit: "units" },
  { name: "Haribo Goldbears 160g", price: 1.55, brand: "Haribo", category: "snacks & sweets", weight: 160, weightUnit: "g" },
  { name: "SuperValu Chocolate Chip Cookies 200g", price: 1.35, brand: "SuperValu", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "KitKat 4 Finger 41.5g", price: 1.05, brand: "KitKat", category: "snacks & sweets", weight: 41.5, weightUnit: "g" },
  { name: "SuperValu Trail Mix 200g", price: 2.39, brand: "SuperValu", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  // ── household (15) ──
  { name: "SuperValu Kitchen Roll 2 Pack", price: 2.09, brand: "SuperValu", category: "household", weight: 2, weightUnit: "units" },
  { name: "SuperValu Toilet Roll 9 Pack", price: 3.89, brand: "SuperValu", category: "household", weight: 9, weightUnit: "units" },
  { name: "SuperValu Toilet Roll 4 Pack", price: 1.99, brand: "SuperValu", category: "household", weight: 4, weightUnit: "units" },
  { name: "Fairy Washing Up Liquid 500ml", price: 2.55, brand: "Fairy", category: "household", weight: 500, weightUnit: "ml" },
  { name: "Persil Laundry Detergent 1.1L", price: 8.19, brand: "Persil", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "SuperValu Laundry Detergent 1.1L", price: 4.19, brand: "SuperValu", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "SuperValu Bin Bags 30 Pack", price: 2.59, brand: "SuperValu", category: "household", weight: 30, weightUnit: "units" },
  { name: "SuperValu Dishwasher Tablets 30 Pack", price: 4.09, brand: "SuperValu", category: "household", weight: 30, weightUnit: "units" },
  { name: "Finish Dishwasher Tablets 50 Pack", price: 9.19, brand: "Finish", category: "household", weight: 50, weightUnit: "units" },
  { name: "SuperValu Antibacterial Surface Spray 750ml", price: 1.55, brand: "SuperValu", category: "household", weight: 750, weightUnit: "ml" },
  { name: "SuperValu Hand Soap 250ml", price: 0.85, brand: "SuperValu", category: "household", weight: 250, weightUnit: "ml" },
  { name: "SuperValu Fabric Conditioner 1.5L", price: 2.59, brand: "SuperValu", category: "household", weight: 1.5, weightUnit: "l" },
  { name: "SuperValu Cling Film 30m", price: 1.35, brand: "SuperValu", category: "household", weight: 30, weightUnit: "units" },
  { name: "SuperValu Tin Foil 10m", price: 1.55, brand: "SuperValu", category: "household", weight: 10, weightUnit: "units" },
  { name: "SuperValu Sponge Scourers 4 Pack", price: 1.05, brand: "SuperValu", category: "household", weight: 4, weightUnit: "units" },
  // ── personal care (10) ──
  { name: "SuperValu Shampoo 400ml", price: 1.55, brand: "SuperValu", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Head & Shoulders Shampoo 250ml", price: 4.09, brand: "Head & Shoulders", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "SuperValu Shower Gel 400ml", price: 1.35, brand: "SuperValu", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Dove Shower Gel 250ml", price: 3.09, brand: "Dove", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Colgate Total Toothpaste 75ml", price: 2.55, brand: "Colgate", category: "personal care", weight: 75, weightUnit: "ml" },
  { name: "SuperValu Toothpaste 100ml", price: 0.95, brand: "SuperValu", category: "personal care", weight: 100, weightUnit: "ml" },
  { name: "Sure Antiperspirant 150ml", price: 3.09, brand: "Sure", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "SuperValu Deodorant 150ml", price: 1.35, brand: "SuperValu", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "SuperValu Facial Tissues 100 Pack", price: 1.05, brand: "SuperValu", category: "personal care", weight: 100, weightUnit: "units" },
  { name: "SuperValu Cotton Pads 100 Pack", price: 1.25, brand: "SuperValu", category: "personal care", weight: 100, weightUnit: "units" },
  // ── baby (5) ──
  { name: "Pampers Baby Dry Nappies Size 4 58 Pack", price: 13.19, brand: "Pampers", category: "baby", weight: 58, weightUnit: "units" },
  { name: "SuperValu Nappies Size 4 50 Pack", price: 8.49, brand: "SuperValu", category: "baby", weight: 50, weightUnit: "units" },
  { name: "WaterWipes Baby Wipes 60 Pack", price: 3.55, brand: "WaterWipes", category: "baby", weight: 60, weightUnit: "units" },
  { name: "Cow & Gate Stage 1 Baby Food 125g", price: 1.35, brand: "Cow & Gate", category: "baby", weight: 125, weightUnit: "g" },
  { name: "Ella's Kitchen Organic Baby Food 120g", price: 1.85, brand: "Ella's Kitchen", category: "baby", weight: 120, weightUnit: "g" },
];

const LIDL_PRODUCTS: ScrapedProduct[] = [
  // ── dairy & eggs (20) ──
  { name: "Lidl Irish Whole Milk 2L", price: 1.89, brand: "Lidl", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Lidl Low Fat Milk 2L", price: 1.85, brand: "Lidl", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Lidl Whole Milk 1L", price: 1.19, brand: "Lidl", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Lidl Skimmed Milk 1L", price: 1.09, brand: "Lidl", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Kerrygold Pure Irish Butter 227g", price: 2.75, brand: "Kerrygold", category: "dairy & eggs", weight: 227, weightUnit: "g" },
  { name: "Lidl Spreadable Butter 500g", price: 3.49, brand: "Lidl", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Lidl Mild Cheddar Cheese 200g", price: 1.89, brand: "Lidl", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Lidl Mature Cheddar Cheese 200g", price: 2.19, brand: "Lidl", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Lidl Grated Mozzarella 250g", price: 1.59, brand: "Lidl", category: "dairy & eggs", weight: 250, weightUnit: "g" },
  { name: "Glenisk Organic Natural Yoghurt 500g", price: 2.35, brand: "Glenisk", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Lidl Greek Style Yoghurt 500g", price: 1.49, brand: "Lidl", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Lidl Natural Yoghurt 500g", price: 0.99, brand: "Lidl", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Lidl Free Range Eggs 10 Pack", price: 2.99, brand: "Lidl", category: "dairy & eggs", weight: 10, weightUnit: "units" },
  { name: "Lidl Free Range Eggs 6 Pack", price: 1.95, brand: "Lidl", category: "dairy & eggs", weight: 6, weightUnit: "units" },
  { name: "Lidl Fresh Cream 250ml", price: 1.29, brand: "Lidl", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Lidl Double Cream 250ml", price: 1.49, brand: "Lidl", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Lidl Cottage Cheese 300g", price: 1.69, brand: "Lidl", category: "dairy & eggs", weight: 300, weightUnit: "g" },
  { name: "Lidl Cream Cheese 200g", price: 1.29, brand: "Lidl", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Lidl Sliced Cheese 150g", price: 1.49, brand: "Lidl", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  { name: "Lidl Parmesan Wedge 150g", price: 2.99, brand: "Lidl", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  // ── meat & poultry (15) ──
  { name: "Lidl Irish Chicken Breast Fillets 360g", price: 4.49, brand: "Lidl", category: "meat & poultry", weight: 360, weightUnit: "g" },
  { name: "Lidl Irish Chicken Thighs 500g", price: 3.29, brand: "Lidl", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Lidl Irish Chicken Drumsticks 500g", price: 2.69, brand: "Lidl", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Lidl Whole Irish Chicken 1.5kg", price: 5.79, brand: "Lidl", category: "meat & poultry", weight: 1.5, weightUnit: "kg" },
  { name: "Lidl Irish Beef Mince 400g", price: 3.99, brand: "Lidl", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Lidl Irish Beef Mince 750g", price: 6.49, brand: "Lidl", category: "meat & poultry", weight: 750, weightUnit: "g" },
  { name: "Lidl Irish Beef Steak 250g", price: 5.29, brand: "Lidl", category: "meat & poultry", weight: 250, weightUnit: "g" },
  { name: "Lidl Streaky Bacon Rashers 200g", price: 2.29, brand: "Lidl", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Lidl Back Bacon Rashers 200g", price: 2.79, brand: "Lidl", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Lidl Irish Pork Sausages 454g", price: 2.49, brand: "Lidl", category: "meat & poultry", weight: 454, weightUnit: "g" },
  { name: "Lidl Cooked Ham Slices 200g", price: 2.69, brand: "Lidl", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Lidl Smoked Salmon 100g", price: 3.99, brand: "Lidl", category: "meat & poultry", weight: 100, weightUnit: "g" },
  { name: "Lidl Fresh Salmon Fillets 260g", price: 5.19, brand: "Lidl", category: "meat & poultry", weight: 260, weightUnit: "g" },
  { name: "Lidl Irish Turkey Mince 400g", price: 3.79, brand: "Lidl", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Lidl Lamb Leg Steak 200g", price: 4.79, brand: "Lidl", category: "meat & poultry", weight: 200, weightUnit: "g" },
  // ── fruits & vegetables (20) ──
  { name: "Lidl Bananas 5 Pack", price: 0.99, brand: "Lidl", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Lidl Royal Gala Apples 6 Pack", price: 1.79, brand: "Lidl", category: "fruits & vegetables", weight: 6, weightUnit: "units" },
  { name: "Lidl Broccoli Head", price: 0.99, brand: "Lidl", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Lidl Carrots 1kg", price: 0.79, brand: "Lidl", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Lidl Rooster Potatoes 2.5kg", price: 2.49, brand: "Lidl", category: "fruits & vegetables", weight: 2.5, weightUnit: "kg" },
  { name: "Lidl White Potatoes 2kg", price: 1.79, brand: "Lidl", category: "fruits & vegetables", weight: 2, weightUnit: "kg" },
  { name: "Lidl Iceberg Lettuce", price: 0.89, brand: "Lidl", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Lidl Vine Tomatoes 450g", price: 1.49, brand: "Lidl", category: "fruits & vegetables", weight: 450, weightUnit: "g" },
  { name: "Lidl Brown Onions 1kg", price: 0.89, brand: "Lidl", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Lidl Closed Cup Mushrooms 250g", price: 1.09, brand: "Lidl", category: "fruits & vegetables", weight: 250, weightUnit: "g" },
  { name: "Lidl Red Peppers 3 Pack", price: 1.59, brand: "Lidl", category: "fruits & vegetables", weight: 3, weightUnit: "units" },
  { name: "Lidl Avocados 2 Pack", price: 1.79, brand: "Lidl", category: "fruits & vegetables", weight: 2, weightUnit: "units" },
  { name: "Lidl Strawberries 400g", price: 2.79, brand: "Lidl", category: "fruits & vegetables", weight: 400, weightUnit: "g" },
  { name: "Lidl Blueberries 150g", price: 2.29, brand: "Lidl", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Lidl Raspberries 150g", price: 2.79, brand: "Lidl", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Lidl Cucumber", price: 0.69, brand: "Lidl", category: "fruits & vegetables", weight: 1, weightUnit: "units" },
  { name: "Lidl Baby Spinach 100g", price: 1.49, brand: "Lidl", category: "fruits & vegetables", weight: 100, weightUnit: "g" },
  { name: "Lidl Courgettes 500g", price: 1.19, brand: "Lidl", category: "fruits & vegetables", weight: 500, weightUnit: "g" },
  { name: "Lidl Lemons 5 Pack", price: 1.39, brand: "Lidl", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Lidl Mixed Salad Bag 120g", price: 1.39, brand: "Lidl", category: "fruits & vegetables", weight: 120, weightUnit: "g" },
  // ── bakery (12) ──
  { name: "Lidl White Sliced Pan 800g", price: 1.19, brand: "Lidl", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Lidl Wholemeal Sliced Pan 800g", price: 1.29, brand: "Lidl", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Family Pan 800g", price: 2.05, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Wholemeal Bread 800g", price: 2.15, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Lidl 4 Butter Croissants", price: 1.49, brand: "Lidl", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Lidl Sourdough Bread 500g", price: 1.79, brand: "Lidl", category: "bakery", weight: 500, weightUnit: "g" },
  { name: "Lidl Soft White Rolls 6 Pack", price: 1.09, brand: "Lidl", category: "bakery", weight: 6, weightUnit: "units" },
  { name: "Lidl Tortilla Wraps 8 Pack", price: 1.39, brand: "Lidl", category: "bakery", weight: 8, weightUnit: "units" },
  { name: "Lidl Scones 4 Pack", price: 1.29, brand: "Lidl", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Lidl Bagels 5 Pack", price: 1.19, brand: "Lidl", category: "bakery", weight: 5, weightUnit: "units" },
  { name: "Lidl Garlic Bread Baguette 270g", price: 1.29, brand: "Lidl", category: "bakery", weight: 270, weightUnit: "g" },
  { name: "Johnston Mooney & OBrien Batch Loaf 800g", price: 2.19, brand: "Johnston Mooney", category: "bakery", weight: 800, weightUnit: "g" },
  // ── drinks (20) ──
  { name: "Lidl Still Water 2L", price: 0.45, brand: "Lidl", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Lidl Still Water 500ml", price: 0.29, brand: "Lidl", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Lidl Orange Juice 1L", price: 1.69, brand: "Lidl", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Lidl Apple Juice 1L", price: 1.49, brand: "Lidl", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Barry's Gold Blend Tea 80s", price: 3.99, brand: "Barry's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Lyon's Original Tea 80s", price: 3.79, brand: "Lyon's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Nescafé Original Instant Coffee 200g", price: 6.79, brand: "Nescafé", category: "drinks", weight: 200, weightUnit: "g" },
  { name: "Coca-Cola 2L", price: 2.69, brand: "Coca-Cola", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Coca-Cola 6 Pack 330ml", price: 4.79, brand: "Coca-Cola", category: "drinks", weight: 6, weightUnit: "units" },
  { name: "Lidl Cola 2L", price: 0.85, brand: "Lidl", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Club Orange 2L", price: 2.39, brand: "Club", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Lucozade Energy Original 1L", price: 2.59, brand: "Lucozade", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Monster Energy 500ml", price: 1.89, brand: "Monster", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Lidl Oat Milk 1L", price: 1.69, brand: "Lidl", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Lidl Almond Milk 1L", price: 1.59, brand: "Lidl", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Lidl Sparkling Water 2L", price: 0.45, brand: "Lidl", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Robinsons Orange Squash 1L", price: 2.39, brand: "Robinsons", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tropicana Orange Juice 950ml", price: 3.29, brand: "Tropicana", category: "drinks", weight: 950, weightUnit: "ml" },
  { name: "Lidl Cranberry Juice 1L", price: 1.69, brand: "Lidl", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Ballygowan Still Water 2L", price: 1.19, brand: "Ballygowan", category: "drinks", weight: 2, weightUnit: "l" },
  // ── frozen (15) ──
  { name: "Birds Eye Fish Fingers 450g", price: 3.79, brand: "Birds Eye", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Lidl Fish Fingers 450g", price: 2.49, brand: "Lidl", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Lidl Frozen Pizza Margherita 300g", price: 1.69, brand: "Lidl", category: "frozen", weight: 300, weightUnit: "g" },
  { name: "Chicago Town Pepperoni Pizza 400g", price: 3.29, brand: "Chicago Town", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Lidl Frozen Chips 1.5kg", price: 1.99, brand: "Lidl", category: "frozen", weight: 1.5, weightUnit: "kg" },
  { name: "HB Vanilla Ice Cream 900ml", price: 3.79, brand: "HB", category: "frozen", weight: 900, weightUnit: "ml" },
  { name: "Ben & Jerrys Cookie Dough 465ml", price: 5.79, brand: "Ben & Jerrys", category: "frozen", weight: 465, weightUnit: "ml" },
  { name: "Lidl Frozen Garden Peas 900g", price: 1.29, brand: "Lidl", category: "frozen", weight: 900, weightUnit: "g" },
  { name: "Lidl Frozen Mixed Vegetables 1kg", price: 1.49, brand: "Lidl", category: "frozen", weight: 1, weightUnit: "kg" },
  { name: "Lidl Frozen Chicken Goujons 400g", price: 2.79, brand: "Lidl", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Lidl Frozen Lasagne 400g", price: 2.09, brand: "Lidl", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Lidl Frozen Shepherd Pie 400g", price: 1.99, brand: "Lidl", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Lidl Frozen Waffles 12 Pack", price: 1.59, brand: "Lidl", category: "frozen", weight: 12, weightUnit: "units" },
  { name: "Lidl Frozen Prawns 250g", price: 4.19, brand: "Lidl", category: "frozen", weight: 250, weightUnit: "g" },
  { name: "Lidl Frozen Battered Cod 400g", price: 3.29, brand: "Lidl", category: "frozen", weight: 400, weightUnit: "g" },
  // ── snacks & sweets (15) ──
  { name: "Cadbury Dairy Milk 200g", price: 2.29, brand: "Cadbury", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Cadbury Bournville Dark Chocolate 180g", price: 2.09, brand: "Cadbury", category: "snacks & sweets", weight: 180, weightUnit: "g" },
  { name: "Lidl Dark Chocolate 100g", price: 0.99, brand: "Lidl", category: "snacks & sweets", weight: 100, weightUnit: "g" },
  { name: "Lidl Milk Chocolate Bar 200g", price: 1.29, brand: "Lidl", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tayto Cheese & Onion Multipack 12 Pack", price: 4.29, brand: "Tayto", category: "snacks & sweets", weight: 12, weightUnit: "units" },
  { name: "Pringles Original 165g", price: 2.79, brand: "Pringles", category: "snacks & sweets", weight: 165, weightUnit: "g" },
  { name: "Lidl Digestive Biscuits 400g", price: 0.99, brand: "Lidl", category: "snacks & sweets", weight: 400, weightUnit: "g" },
  { name: "McVities Chocolate Digestives 300g", price: 2.05, brand: "McVities", category: "snacks & sweets", weight: 300, weightUnit: "g" },
  { name: "Lidl Salted Cashews 200g", price: 2.59, brand: "Lidl", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Lidl Mixed Nuts 200g", price: 2.29, brand: "Lidl", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Lidl Sweet Microwave Popcorn 3 Pack", price: 1.09, brand: "Lidl", category: "snacks & sweets", weight: 3, weightUnit: "units" },
  { name: "Haribo Goldbears 160g", price: 1.39, brand: "Haribo", category: "snacks & sweets", weight: 160, weightUnit: "g" },
  { name: "Lidl Chocolate Chip Cookies 200g", price: 1.09, brand: "Lidl", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "KitKat 4 Finger 41.5g", price: 0.89, brand: "KitKat", category: "snacks & sweets", weight: 41.5, weightUnit: "g" },
  { name: "Lidl Trail Mix 200g", price: 2.09, brand: "Lidl", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  // ── household (15) ──
  { name: "Lidl Kitchen Roll 2 Pack", price: 1.79, brand: "Lidl", category: "household", weight: 2, weightUnit: "units" },
  { name: "Lidl Toilet Roll 9 Pack", price: 3.49, brand: "Lidl", category: "household", weight: 9, weightUnit: "units" },
  { name: "Lidl Toilet Roll 4 Pack", price: 1.69, brand: "Lidl", category: "household", weight: 4, weightUnit: "units" },
  { name: "Fairy Washing Up Liquid 500ml", price: 2.29, brand: "Fairy", category: "household", weight: 500, weightUnit: "ml" },
  { name: "Persil Laundry Detergent 1.1L", price: 7.69, brand: "Persil", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Lidl Laundry Detergent 1.1L", price: 3.79, brand: "Lidl", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Lidl Bin Bags 30 Pack", price: 2.29, brand: "Lidl", category: "household", weight: 30, weightUnit: "units" },
  { name: "Lidl Dishwasher Tablets 30 Pack", price: 3.79, brand: "Lidl", category: "household", weight: 30, weightUnit: "units" },
  { name: "Finish Dishwasher Tablets 50 Pack", price: 8.79, brand: "Finish", category: "household", weight: 50, weightUnit: "units" },
  { name: "Lidl Antibacterial Surface Spray 750ml", price: 1.29, brand: "Lidl", category: "household", weight: 750, weightUnit: "ml" },
  { name: "Lidl Hand Soap 250ml", price: 0.69, brand: "Lidl", category: "household", weight: 250, weightUnit: "ml" },
  { name: "Lidl Fabric Conditioner 1.5L", price: 2.29, brand: "Lidl", category: "household", weight: 1.5, weightUnit: "l" },
  { name: "Lidl Cling Film 30m", price: 1.09, brand: "Lidl", category: "household", weight: 30, weightUnit: "units" },
  { name: "Lidl Tin Foil 10m", price: 1.29, brand: "Lidl", category: "household", weight: 10, weightUnit: "units" },
  { name: "Lidl Sponge Scourers 4 Pack", price: 0.79, brand: "Lidl", category: "household", weight: 4, weightUnit: "units" },
  // ── personal care (10) ──
  { name: "Lidl Shampoo 400ml", price: 1.29, brand: "Lidl", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Head & Shoulders Shampoo 250ml", price: 3.79, brand: "Head & Shoulders", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Lidl Shower Gel 400ml", price: 1.09, brand: "Lidl", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Dove Shower Gel 250ml", price: 2.79, brand: "Dove", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Colgate Total Toothpaste 75ml", price: 2.29, brand: "Colgate", category: "personal care", weight: 75, weightUnit: "ml" },
  { name: "Lidl Toothpaste 100ml", price: 0.79, brand: "Lidl", category: "personal care", weight: 100, weightUnit: "ml" },
  { name: "Sure Antiperspirant 150ml", price: 2.79, brand: "Sure", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Lidl Deodorant 150ml", price: 1.09, brand: "Lidl", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Lidl Facial Tissues 100 Pack", price: 0.79, brand: "Lidl", category: "personal care", weight: 100, weightUnit: "units" },
  { name: "Lidl Cotton Pads 100 Pack", price: 0.99, brand: "Lidl", category: "personal care", weight: 100, weightUnit: "units" },
  // ── baby (5) ──
  { name: "Pampers Baby Dry Nappies Size 4 58 Pack", price: 12.49, brand: "Pampers", category: "baby", weight: 58, weightUnit: "units" },
  { name: "Lidl Nappies Size 4 50 Pack", price: 6.99, brand: "Lidl", category: "baby", weight: 50, weightUnit: "units" },
  { name: "WaterWipes Baby Wipes 60 Pack", price: 3.29, brand: "WaterWipes", category: "baby", weight: 60, weightUnit: "units" },
  { name: "Cow & Gate Stage 1 Baby Food 125g", price: 1.19, brand: "Cow & Gate", category: "baby", weight: 125, weightUnit: "g" },
  { name: "Ella's Kitchen Organic Baby Food 120g", price: 1.69, brand: "Ella's Kitchen", category: "baby", weight: 120, weightUnit: "g" },
];

const ALDI_PRODUCTS: ScrapedProduct[] = [
  // ── dairy & eggs (20) ──
  { name: "Aldi Irish Whole Milk 2L", price: 1.85, brand: "Aldi", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Aldi Low Fat Milk 2L", price: 1.79, brand: "Aldi", category: "dairy & eggs", weight: 2, weightUnit: "l" },
  { name: "Aldi Whole Milk 1L", price: 1.15, brand: "Aldi", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Aldi Skimmed Milk 1L", price: 1.09, brand: "Aldi", category: "dairy & eggs", weight: 1, weightUnit: "l" },
  { name: "Kerrygold Pure Irish Butter 227g", price: 2.69, brand: "Kerrygold", category: "dairy & eggs", weight: 227, weightUnit: "g" },
  { name: "Aldi Spreadable Butter 500g", price: 3.39, brand: "Aldi", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Aldi Mild Cheddar Cheese 200g", price: 1.85, brand: "Aldi", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Aldi Mature Cheddar Cheese 200g", price: 2.15, brand: "Aldi", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Aldi Grated Mozzarella 250g", price: 1.55, brand: "Aldi", category: "dairy & eggs", weight: 250, weightUnit: "g" },
  { name: "Glenisk Organic Natural Yoghurt 500g", price: 2.29, brand: "Glenisk", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Aldi Greek Style Yoghurt 500g", price: 1.39, brand: "Aldi", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Aldi Natural Yoghurt 500g", price: 0.95, brand: "Aldi", category: "dairy & eggs", weight: 500, weightUnit: "g" },
  { name: "Aldi Free Range Eggs 10 Pack", price: 2.89, brand: "Aldi", category: "dairy & eggs", weight: 10, weightUnit: "units" },
  { name: "Aldi Free Range Eggs 6 Pack", price: 1.89, brand: "Aldi", category: "dairy & eggs", weight: 6, weightUnit: "units" },
  { name: "Aldi Fresh Cream 250ml", price: 1.25, brand: "Aldi", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Aldi Double Cream 250ml", price: 1.45, brand: "Aldi", category: "dairy & eggs", weight: 250, weightUnit: "ml" },
  { name: "Aldi Cottage Cheese 300g", price: 1.65, brand: "Aldi", category: "dairy & eggs", weight: 300, weightUnit: "g" },
  { name: "Aldi Cream Cheese 200g", price: 1.25, brand: "Aldi", category: "dairy & eggs", weight: 200, weightUnit: "g" },
  { name: "Aldi Sliced Cheese 150g", price: 1.45, brand: "Aldi", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  { name: "Aldi Parmesan Wedge 150g", price: 2.89, brand: "Aldi", category: "dairy & eggs", weight: 150, weightUnit: "g" },
  // ── meat & poultry (15) ──
  { name: "Aldi Irish Chicken Breast Fillets 360g", price: 4.39, brand: "Aldi", category: "meat & poultry", weight: 360, weightUnit: "g" },
  { name: "Aldi Irish Chicken Thighs 500g", price: 3.19, brand: "Aldi", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Aldi Irish Chicken Drumsticks 500g", price: 2.65, brand: "Aldi", category: "meat & poultry", weight: 500, weightUnit: "g" },
  { name: "Aldi Whole Irish Chicken 1.5kg", price: 5.69, brand: "Aldi", category: "meat & poultry", weight: 1.5, weightUnit: "kg" },
  { name: "Aldi Irish Beef Mince 400g", price: 3.89, brand: "Aldi", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Aldi Irish Beef Mince 750g", price: 6.29, brand: "Aldi", category: "meat & poultry", weight: 750, weightUnit: "g" },
  { name: "Aldi Irish Beef Steak 250g", price: 5.19, brand: "Aldi", category: "meat & poultry", weight: 250, weightUnit: "g" },
  { name: "Aldi Streaky Bacon Rashers 200g", price: 2.19, brand: "Aldi", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Aldi Back Bacon Rashers 200g", price: 2.69, brand: "Aldi", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Aldi Irish Pork Sausages 454g", price: 2.39, brand: "Aldi", category: "meat & poultry", weight: 454, weightUnit: "g" },
  { name: "Aldi Cooked Ham Slices 200g", price: 2.59, brand: "Aldi", category: "meat & poultry", weight: 200, weightUnit: "g" },
  { name: "Aldi Smoked Salmon 100g", price: 3.89, brand: "Aldi", category: "meat & poultry", weight: 100, weightUnit: "g" },
  { name: "Aldi Fresh Salmon Fillets 260g", price: 5.09, brand: "Aldi", category: "meat & poultry", weight: 260, weightUnit: "g" },
  { name: "Aldi Irish Turkey Mince 400g", price: 3.69, brand: "Aldi", category: "meat & poultry", weight: 400, weightUnit: "g" },
  { name: "Aldi Lamb Leg Steak 200g", price: 4.69, brand: "Aldi", category: "meat & poultry", weight: 200, weightUnit: "g" },
  // ── fruits & vegetables (20) ──
  { name: "Aldi Bananas 5 Pack", price: 0.95, brand: "Aldi", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Aldi Royal Gala Apples 6 Pack", price: 1.75, brand: "Aldi", category: "fruits & vegetables", weight: 6, weightUnit: "units" },
  { name: "Aldi Broccoli Head", price: 0.95, brand: "Aldi", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Aldi Carrots 1kg", price: 0.75, brand: "Aldi", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Aldi Rooster Potatoes 2.5kg", price: 2.39, brand: "Aldi", category: "fruits & vegetables", weight: 2.5, weightUnit: "kg" },
  { name: "Aldi White Potatoes 2kg", price: 1.69, brand: "Aldi", category: "fruits & vegetables", weight: 2, weightUnit: "kg" },
  { name: "Aldi Iceberg Lettuce", price: 0.85, brand: "Aldi", category: "fruits & vegetables", weight: 300, weightUnit: "g" },
  { name: "Aldi Vine Tomatoes 450g", price: 1.39, brand: "Aldi", category: "fruits & vegetables", weight: 450, weightUnit: "g" },
  { name: "Aldi Brown Onions 1kg", price: 0.85, brand: "Aldi", category: "fruits & vegetables", weight: 1, weightUnit: "kg" },
  { name: "Aldi Closed Cup Mushrooms 250g", price: 1.05, brand: "Aldi", category: "fruits & vegetables", weight: 250, weightUnit: "g" },
  { name: "Aldi Red Peppers 3 Pack", price: 1.55, brand: "Aldi", category: "fruits & vegetables", weight: 3, weightUnit: "units" },
  { name: "Aldi Avocados 2 Pack", price: 1.75, brand: "Aldi", category: "fruits & vegetables", weight: 2, weightUnit: "units" },
  { name: "Aldi Strawberries 400g", price: 2.69, brand: "Aldi", category: "fruits & vegetables", weight: 400, weightUnit: "g" },
  { name: "Aldi Blueberries 150g", price: 2.19, brand: "Aldi", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Aldi Raspberries 150g", price: 2.69, brand: "Aldi", category: "fruits & vegetables", weight: 150, weightUnit: "g" },
  { name: "Aldi Cucumber", price: 0.65, brand: "Aldi", category: "fruits & vegetables", weight: 1, weightUnit: "units" },
  { name: "Aldi Baby Spinach 100g", price: 1.45, brand: "Aldi", category: "fruits & vegetables", weight: 100, weightUnit: "g" },
  { name: "Aldi Courgettes 500g", price: 1.15, brand: "Aldi", category: "fruits & vegetables", weight: 500, weightUnit: "g" },
  { name: "Aldi Lemons 5 Pack", price: 1.35, brand: "Aldi", category: "fruits & vegetables", weight: 5, weightUnit: "units" },
  { name: "Aldi Mixed Salad Bag 120g", price: 1.35, brand: "Aldi", category: "fruits & vegetables", weight: 120, weightUnit: "g" },
  // ── bakery (12) ──
  { name: "Aldi White Sliced Pan 800g", price: 1.15, brand: "Aldi", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Aldi Wholemeal Sliced Pan 800g", price: 1.25, brand: "Aldi", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Family Pan 800g", price: 1.99, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Brennans Wholemeal Bread 800g", price: 2.09, brand: "Brennans", category: "bakery", weight: 800, weightUnit: "g" },
  { name: "Aldi 4 Butter Croissants", price: 1.39, brand: "Aldi", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Aldi Sourdough Bread 500g", price: 1.75, brand: "Aldi", category: "bakery", weight: 500, weightUnit: "g" },
  { name: "Aldi Soft White Rolls 6 Pack", price: 1.05, brand: "Aldi", category: "bakery", weight: 6, weightUnit: "units" },
  { name: "Aldi Tortilla Wraps 8 Pack", price: 1.35, brand: "Aldi", category: "bakery", weight: 8, weightUnit: "units" },
  { name: "Aldi Scones 4 Pack", price: 1.25, brand: "Aldi", category: "bakery", weight: 4, weightUnit: "units" },
  { name: "Aldi Bagels 5 Pack", price: 1.15, brand: "Aldi", category: "bakery", weight: 5, weightUnit: "units" },
  { name: "Aldi Garlic Bread Baguette 270g", price: 1.25, brand: "Aldi", category: "bakery", weight: 270, weightUnit: "g" },
  { name: "Johnston Mooney & OBrien Batch Loaf 800g", price: 2.19, brand: "Johnston Mooney", category: "bakery", weight: 800, weightUnit: "g" },
  // ── drinks (20) ──
  { name: "Aldi Still Water 2L", price: 0.45, brand: "Aldi", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Aldi Still Water 500ml", price: 0.29, brand: "Aldi", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Aldi Orange Juice 1L", price: 1.59, brand: "Aldi", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Aldi Apple Juice 1L", price: 1.39, brand: "Aldi", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Barry's Gold Blend Tea 80s", price: 3.89, brand: "Barry's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Lyon's Original Tea 80s", price: 3.69, brand: "Lyon's", category: "drinks", weight: 80, weightUnit: "units" },
  { name: "Nescafé Original Instant Coffee 200g", price: 6.69, brand: "Nescafé", category: "drinks", weight: 200, weightUnit: "g" },
  { name: "Coca-Cola 2L", price: 2.65, brand: "Coca-Cola", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Coca-Cola 6 Pack 330ml", price: 4.75, brand: "Coca-Cola", category: "drinks", weight: 6, weightUnit: "units" },
  { name: "Aldi Cola 2L", price: 0.79, brand: "Aldi", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Club Orange 2L", price: 2.35, brand: "Club", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Lucozade Energy Original 1L", price: 2.55, brand: "Lucozade", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Monster Energy 500ml", price: 1.85, brand: "Monster", category: "drinks", weight: 500, weightUnit: "ml" },
  { name: "Aldi Oat Milk 1L", price: 1.65, brand: "Aldi", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Aldi Almond Milk 1L", price: 1.55, brand: "Aldi", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Aldi Sparkling Water 2L", price: 0.45, brand: "Aldi", category: "drinks", weight: 2, weightUnit: "l" },
  { name: "Robinsons Orange Squash 1L", price: 2.35, brand: "Robinsons", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Tropicana Orange Juice 950ml", price: 3.25, brand: "Tropicana", category: "drinks", weight: 950, weightUnit: "ml" },
  { name: "Aldi Cranberry Juice 1L", price: 1.65, brand: "Aldi", category: "drinks", weight: 1, weightUnit: "l" },
  { name: "Ballygowan Still Water 2L", price: 1.15, brand: "Ballygowan", category: "drinks", weight: 2, weightUnit: "l" },
  // ── frozen (15) ──
  { name: "Birds Eye Fish Fingers 450g", price: 3.69, brand: "Birds Eye", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Aldi Fish Fingers 450g", price: 2.39, brand: "Aldi", category: "frozen", weight: 450, weightUnit: "g" },
  { name: "Aldi Frozen Pizza Margherita 300g", price: 1.59, brand: "Aldi", category: "frozen", weight: 300, weightUnit: "g" },
  { name: "Chicago Town Pepperoni Pizza 400g", price: 3.19, brand: "Chicago Town", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Aldi Frozen Chips 1.5kg", price: 1.89, brand: "Aldi", category: "frozen", weight: 1.5, weightUnit: "kg" },
  { name: "HB Vanilla Ice Cream 900ml", price: 3.69, brand: "HB", category: "frozen", weight: 900, weightUnit: "ml" },
  { name: "Ben & Jerrys Cookie Dough 465ml", price: 5.69, brand: "Ben & Jerrys", category: "frozen", weight: 465, weightUnit: "ml" },
  { name: "Aldi Frozen Garden Peas 900g", price: 1.25, brand: "Aldi", category: "frozen", weight: 900, weightUnit: "g" },
  { name: "Aldi Frozen Mixed Vegetables 1kg", price: 1.45, brand: "Aldi", category: "frozen", weight: 1, weightUnit: "kg" },
  { name: "Aldi Frozen Chicken Goujons 400g", price: 2.69, brand: "Aldi", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Aldi Frozen Lasagne 400g", price: 1.99, brand: "Aldi", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Aldi Frozen Shepherd Pie 400g", price: 1.89, brand: "Aldi", category: "frozen", weight: 400, weightUnit: "g" },
  { name: "Aldi Frozen Waffles 12 Pack", price: 1.55, brand: "Aldi", category: "frozen", weight: 12, weightUnit: "units" },
  { name: "Aldi Frozen Prawns 250g", price: 4.09, brand: "Aldi", category: "frozen", weight: 250, weightUnit: "g" },
  { name: "Aldi Frozen Battered Cod 400g", price: 3.19, brand: "Aldi", category: "frozen", weight: 400, weightUnit: "g" },
  // ── snacks & sweets (15) ──
  { name: "Cadbury Dairy Milk 200g", price: 2.25, brand: "Cadbury", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Cadbury Bournville Dark Chocolate 180g", price: 2.05, brand: "Cadbury", category: "snacks & sweets", weight: 180, weightUnit: "g" },
  { name: "Aldi Dark Chocolate 100g", price: 0.95, brand: "Aldi", category: "snacks & sweets", weight: 100, weightUnit: "g" },
  { name: "Aldi Milk Chocolate Bar 200g", price: 1.25, brand: "Aldi", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Tayto Cheese & Onion Multipack 12 Pack", price: 4.25, brand: "Tayto", category: "snacks & sweets", weight: 12, weightUnit: "units" },
  { name: "Pringles Original 165g", price: 2.75, brand: "Pringles", category: "snacks & sweets", weight: 165, weightUnit: "g" },
  { name: "Aldi Digestive Biscuits 400g", price: 0.95, brand: "Aldi", category: "snacks & sweets", weight: 400, weightUnit: "g" },
  { name: "McVities Chocolate Digestives 300g", price: 1.99, brand: "McVities", category: "snacks & sweets", weight: 300, weightUnit: "g" },
  { name: "Aldi Salted Cashews 200g", price: 2.49, brand: "Aldi", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Aldi Mixed Nuts 200g", price: 2.19, brand: "Aldi", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "Aldi Sweet Microwave Popcorn 3 Pack", price: 1.05, brand: "Aldi", category: "snacks & sweets", weight: 3, weightUnit: "units" },
  { name: "Haribo Goldbears 160g", price: 1.35, brand: "Haribo", category: "snacks & sweets", weight: 160, weightUnit: "g" },
  { name: "Aldi Chocolate Chip Cookies 200g", price: 1.05, brand: "Aldi", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  { name: "KitKat 4 Finger 41.5g", price: 0.85, brand: "KitKat", category: "snacks & sweets", weight: 41.5, weightUnit: "g" },
  { name: "Aldi Trail Mix 200g", price: 2.05, brand: "Aldi", category: "snacks & sweets", weight: 200, weightUnit: "g" },
  // ── household (15) ──
  { name: "Aldi Kitchen Roll 2 Pack", price: 1.69, brand: "Aldi", category: "household", weight: 2, weightUnit: "units" },
  { name: "Aldi Toilet Roll 9 Pack", price: 3.29, brand: "Aldi", category: "household", weight: 9, weightUnit: "units" },
  { name: "Aldi Toilet Roll 4 Pack", price: 1.59, brand: "Aldi", category: "household", weight: 4, weightUnit: "units" },
  { name: "Fairy Washing Up Liquid 500ml", price: 2.25, brand: "Fairy", category: "household", weight: 500, weightUnit: "ml" },
  { name: "Persil Laundry Detergent 1.1L", price: 7.59, brand: "Persil", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Aldi Laundry Detergent 1.1L", price: 3.69, brand: "Aldi", category: "household", weight: 1.1, weightUnit: "l" },
  { name: "Aldi Bin Bags 30 Pack", price: 2.19, brand: "Aldi", category: "household", weight: 30, weightUnit: "units" },
  { name: "Aldi Dishwasher Tablets 30 Pack", price: 3.69, brand: "Aldi", category: "household", weight: 30, weightUnit: "units" },
  { name: "Finish Dishwasher Tablets 50 Pack", price: 8.69, brand: "Finish", category: "household", weight: 50, weightUnit: "units" },
  { name: "Aldi Antibacterial Surface Spray 750ml", price: 1.25, brand: "Aldi", category: "household", weight: 750, weightUnit: "ml" },
  { name: "Aldi Hand Soap 250ml", price: 0.65, brand: "Aldi", category: "household", weight: 250, weightUnit: "ml" },
  { name: "Aldi Fabric Conditioner 1.5L", price: 2.19, brand: "Aldi", category: "household", weight: 1.5, weightUnit: "l" },
  { name: "Aldi Cling Film 30m", price: 1.05, brand: "Aldi", category: "household", weight: 30, weightUnit: "units" },
  { name: "Aldi Tin Foil 10m", price: 1.25, brand: "Aldi", category: "household", weight: 10, weightUnit: "units" },
  { name: "Aldi Sponge Scourers 4 Pack", price: 0.75, brand: "Aldi", category: "household", weight: 4, weightUnit: "units" },
  // ── personal care (10) ──
  { name: "Aldi Shampoo 400ml", price: 1.25, brand: "Aldi", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Head & Shoulders Shampoo 250ml", price: 3.69, brand: "Head & Shoulders", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Aldi Shower Gel 400ml", price: 1.05, brand: "Aldi", category: "personal care", weight: 400, weightUnit: "ml" },
  { name: "Dove Shower Gel 250ml", price: 2.75, brand: "Dove", category: "personal care", weight: 250, weightUnit: "ml" },
  { name: "Colgate Total Toothpaste 75ml", price: 2.25, brand: "Colgate", category: "personal care", weight: 75, weightUnit: "ml" },
  { name: "Aldi Toothpaste 100ml", price: 0.75, brand: "Aldi", category: "personal care", weight: 100, weightUnit: "ml" },
  { name: "Sure Antiperspirant 150ml", price: 2.75, brand: "Sure", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Aldi Deodorant 150ml", price: 1.05, brand: "Aldi", category: "personal care", weight: 150, weightUnit: "ml" },
  { name: "Aldi Facial Tissues 100 Pack", price: 0.75, brand: "Aldi", category: "personal care", weight: 100, weightUnit: "units" },
  { name: "Aldi Cotton Pads 100 Pack", price: 0.95, brand: "Aldi", category: "personal care", weight: 100, weightUnit: "units" },
  // ── baby (5) ──
  { name: "Pampers Baby Dry Nappies Size 4 58 Pack", price: 12.39, brand: "Pampers", category: "baby", weight: 58, weightUnit: "units" },
  { name: "Aldi Nappies Size 4 50 Pack", price: 6.79, brand: "Aldi", category: "baby", weight: 50, weightUnit: "units" },
  { name: "WaterWipes Baby Wipes 60 Pack", price: 3.25, brand: "WaterWipes", category: "baby", weight: 60, weightUnit: "units" },
  { name: "Cow & Gate Stage 1 Baby Food 125g", price: 1.15, brand: "Cow & Gate", category: "baby", weight: 125, weightUnit: "g" },
  { name: "Ella's Kitchen Organic Baby Food 120g", price: 1.65, brand: "Ella's Kitchen", category: "baby", weight: 120, weightUnit: "g" },
];

export const STORE_PRODUCTS: Record<string, ScrapedProduct[]> = {
  tesco: TESCO_PRODUCTS,
  dunnes: DUNNES_PRODUCTS,
  supervalu: SUPERVALU_PRODUCTS,
  lidl: LIDL_PRODUCTS,
  aldi: ALDI_PRODUCTS,
};

/** Returns curated (fallback) products for a store. */
export function getProductsForStore(storeSlug: string): ScrapedProduct[] {
  return STORE_PRODUCTS[storeSlug] || [];
}

/** Attempts live scraping, falling back to curated data. */
export async function scrapeStore(
  storeSlug: string
): Promise<{ products: ScrapedProduct[]; source: "live" | "fallback"; error?: string }> {
  const { scrapeTesco } = await import("./tesco");
  const { scrapeDunnes } = await import("./dunnes");
  const { scrapeSuperValu } = await import("./supervalu");
  const { scrapeLidl } = await import("./lidl");
  const { scrapeAldi } = await import("./aldi");

  const fallback = getProductsForStore(storeSlug);

  switch (storeSlug) {
    case "tesco":
      return scrapeTesco(fallback);
    case "dunnes":
      return scrapeDunnes(fallback);
    case "supervalu":
      return scrapeSuperValu(fallback);
    case "lidl":
      return scrapeLidl(fallback);
    case "aldi":
      return scrapeAldi(fallback);
    default:
      return { products: fallback, source: "fallback" };
  }
}

// Re-export matching functions from the new matcher module
export {
  canonicalProductName,
  productMatchSlug,
  normalizeProductName,
  slugify,
} from "./matcher";

export const CATEGORY_MAP: Record<string, string> = {
  "dairy & eggs": "dairy-eggs",
  "meat & poultry": "meat-poultry",
  "fruits & vegetables": "fruits-vegetables",
  "bakery": "bakery",
  "drinks": "drinks",
  "frozen": "frozen",
  "snacks & sweets": "snacks-sweets",
  "pantry & cupboard": "pantry-cupboard",
  "household": "household",
  "personal care": "personal-care",
  "baby": "baby",
};
